import React, { createContext, useContext, useState, useEffect } from 'react';
import { doc, getDoc, setDoc } from "firebase/firestore";
import { db } from './firebase.js';
import { useAuth } from './main.jsx';

const LanguageContext = createContext(null);

// Add all your future translations here!
export const uiTranslations = {
  en: {
    "HISTORY ARCHIVE": "HISTORY ARCHIVE",
    "Search Engine": "Search Engine",
    "DSE Trend Analysis": "DSE Trend Analysis",
    "Student Dashboard": "Student Dashboard",
    "Saved Lists": "Saved Lists",
    "PDF Tools": "PDF Tools",
    "Record Management": "Record Management",
    "Marks Management": "Marks Management",
    "Sign in": "Sign in",
    "Sign Out": "Sign Out",
    "Access Denied": "Access Denied",
    "Admin Mode": "Admin Mode",
    "Viewer Mode": "Viewer Mode",
    "Access": "Access",
    "Samples": "Samples",
    "Upload": "Upload",
    "Access Restricted": "Access Restricted",
    "Unauthorized Access": "Unauthorized Access",
    "Active Filters": "Active Filters",
    "Hide Filters": "Hide Filters",
    "Show Filters": "Show Filters",
    "Manage Tags": "Manage Tags",
    "Reset All": "Reset All",
    "Tier Level (Admin Only)": "Tier Level (Admin Only)",
    "Origin": "Origin",
    "Year": "Year",
    "Paper Type": "Paper Type",
    "Question Type": "Question Type",
    "Source Type": "Source Type",
    "Topics": "Topics",
    "Marks": "Marks",
    "Search topics, types...": "Search topics, types...",
    "View Full Paper": "View Full Paper",
    "View Details": "View Details",
    "Edit Parent": "Edit Parent",
    "Mark as Done": "Mark as Done",
    "Done": "Done",
    "No options available": "No options available",
    "Selected": "Selected",
    "Add another...": "Add another...",
    "No matches found": "No matches found",
    "Start typing to search": "Start typing to search",
    "Add": "Add",
    "Show": "Show",
    "results per page": "results per page",
    "Verifying Access...": "Verifying Access...",
    "Found": "Found",
    "sub-questions": "sub-questions",
    "papers": "papers",
    "Secure Database Access": "Secure Database Access",
    "You must be logged in to view the archive contents.": "You must be logged in to view the archive contents.",
    "Login with Google": "Login with Google",
    "Your account": "Your account",
    "does not have permission to view these documents.": "does not have permission to view these documents.",
    "Please contact the administrator to request access.": "Please contact the administrator to request access.",
    "Select Paper Type first": "Select Paper Type first",
    "Paper 1 (DBQ)": "Paper 1 (DBQ)",
    "Paper 2 (Essay)": "Paper 2 (Essay)",
    "Only available for Paper 1": "Only available for Paper 1",
    "Year (Newest)": "Year (Newest)",
    "Year (Oldest)": "Year (Oldest)",
    "Title (A-Z)": "Title (A-Z)",
    "Date Added (Newest)": "Date Added (Newest)",
    "Topic (A-Z)": "Topic (A-Z)",
    "Question Type (A-Z)": "Question Type (A-Z)",
    "Star / To-Do Later": "Star / To-Do Later",
    "Reports Attached": "Reports Attached",
    "[Extra Practice]": "[Extra Practice]",
    "Contains": "Contains",
    "matched": "matched",
    "Hide Questions": "Hide Questions",
    "Show Questions": "Show Questions",
    "Hide": "Hide",
    "No text content provided.": "No text content provided.",
    "PDF": "PDF",
    "Ans": "Ans",
    "Edit": "Edit",
    "PDF Attached": "PDF Attached",
    "No PDF attached": "No PDF attached",
    "Answer Key Available": "Answer Key Available",
    "View Marks": "View Marks",
    "No questions found matching your criteria.": "No questions found matching your criteria.",
    "Manage Student Samples": "Manage Student Samples",
    "View or delete uploaded student samples organized by year.": "View or delete uploaded student samples organized by year.",
    "Grade:": "Grade:",
    "Tags:": "Tags:",
    "Reported Issue": "Reported Issue",
    "Clear this Report": "Clear this Report",
    "System Update": "System Update",
    "Don't show this again": "Don't show this again",
    "OK, Got it!": "OK, Got it!",
    "Manage Access & Roles": "Manage Access & Roles",
    "Configure users, roles, and automated tier unlocking.": "Configure users, roles, and automated tier unlocking.",
    "Users & Roles": "Users & Roles",
    "Tier Access Control": "Tier Access Control",
    "Google Email Address": "Google Email Address",
    "Role": "Role",
    "Add User": "Add User",
    "Email Address": "Email Address",
    "Actions": "Actions",
    "No users found.": "No users found.",
    "Custom Roles": "Custom Roles",
    "New role name...": "New role name...",
    "Rename Tiers": "Rename Tiers",
    "You can rename tiers here. Ordered 10 (Highest) to 1.": "You can rename tiers here. Ordered 10 (Highest) to 1.",
    "Automated Tier Unlocking": "Automated Tier Unlocking",
    "Select a user role below, then configure the specific date when each tier becomes visible to them.": "Select a user role below, then configure the specific date when each tier becomes visible to them.",
    "You can also check \"Immediate Access\" to grant access right away.": "You can also check \"Immediate Access\" to grant access right away.",
    "Note: Access is cumulative!": "Note: Access is cumulative!",
    "Unlocking a higher tier (e.g., Tier 5) automatically grants access to all lower tiers (1-4).": "Unlocking a higher tier (e.g., Tier 5) automatically grants access to all lower tiers (1-4).",
    "Select Role": "Select Role",
    "Group": "Group",
    "Unlock Dates for:": "Unlock Dates for:",
    "Immediate Access": "Immediate Access",
    "Clear Date": "Clear Date",
    "Bulk Update Document Tiers": "Bulk Update Document Tiers",
    "Force all existing documents in the archive to a specific tier (e.g., your S6 DSE tier).": "Force all existing documents in the archive to a specific tier (e.g., your S6 DSE tier).",
    "Apply to All Documents": "Apply to All Documents",
    "Save All Settings & Access": "Save All Settings & Access",
    "Manage Filter Tags": "Manage Filter Tags",
    "Note:": "Note:",
    "Deleting a tag here removes it from the filter list for this session. To permanently delete a tag, you must edit the questions that contain it.": "Deleting a tag here removes it from the filter list for this session. To permanently delete a tag, you must edit the questions that contain it.",
    "Source Types": "Source Types",
    "Question Types (DBQ)": "Question Types (DBQ)",
    "Question Types (Essay)": "Question Types (Essay)",
    "Answer Key: ": "Answer Key: ",
    "Full Paper View": "Full Paper View",
    "Report": "Report",
    "Answer": "Answer",
    "Back": "Back",
    "View & Download": "View & Download",
    "Download": "Download",
    "Paper Overview": "Paper Overview",
    "All Sub-Questions": "All Sub-Questions",
    "No text content available.": "No text content available.",
    "Question Content": "Question Content",
    "No text content available. Please refer to the PDF.": "No text content available. Please refer to the PDF.",
    "Student Samples": "Student Samples",
    "Mark (High to Low)": "Mark (High to Low)",
    "Language (EN to CH)": "Language (EN to CH)",
    "Both (Lang then Mark)": "Both (Lang then Mark)",
    "There is currently no sample available.": "There is currently no sample available.",
    "Overall grade:": "Overall grade:",
    "Mark (this question): ": "Mark (this question): ",
    "View Sample": "View Sample",
    "View PDF": "View PDF",
    "No answer file available.": "No answer file available.",
    "Select Upload Type": "Select Upload Type",
    "Choose what kind of document you want to add to the archive.": "Choose what kind of document you want to add to the archive.",
    "Edit Question Set": "Edit Question Set",
    "Upload New Question Set": "Upload New Question Set",
    "Add or modify a parent document and its sub-questions.": "Add or modify a parent document and its sub-questions.",
    "Batch Exam Paper Upload": "Batch Exam Paper Upload",
    "Upload a full exam PDF and split it into multiple questions.": "Upload a full exam PDF and split it into multiple questions.",
    "Upload Student Sample": "Upload Student Sample",
    "Upload student answers, assign grades, and link to specific questions.": "Upload student answers, assign grades, and link to specific questions.",
    "Question Set": "Question Set",
    "Upload exam papers, mock tests, and their sub-questions.": "Upload exam papers, mock tests, and their sub-questions.",
    "Batch Exam Paper": "Batch Exam Paper",
    "Upload a full exam PDF, split pages, and categorize multiple DBQ/Essays at once.": "Upload a full exam PDF, split pages, and categorize multiple DBQ/Essays at once.",
    "Student Sample": "Student Sample",
    "Parent Document Details": "Parent Document Details",
    "Document Title": "Document Title",
    "Auto-detects \"2012D\" or \"2013E\"": "Auto-detects \"2012D\" or \"2013E\"",
    "e.g. 2021E (Type '2012D' to auto-select DBQ)": "e.g. 2021E (Type '2012D' to auto-select DBQ)",
    "Select Paper": "Select Paper",
    "Document Tier Level": "Document Tier Level",
    "Main Topic(s) (Paper 1 Only)": "Main Topic(s) (Paper 1 Only)",
    "Not applicable": "Not applicable",
    "Select or type new topic...": "Select or type new topic...",
    "Select Origin": "Select Origin",
    "PDF Document (Question)": "PDF Document (Question)",
    "Optional": "Optional",
    "Selected:": "Selected:",
    "Attach Pending:": "Attach Pending:",
    "Answer Document (PDF)": "Answer Document (PDF)",
    "Sub-Questions (Children)": "Sub-Questions (Children)",
    "Add Question": "Add Question",
    "Label": "Label",
    "Question Type(s)": "Question Type(s)",
    "Select or add type...": "Select or add type...",
    "e.g. 4": "e.g. 4",
    "e.g. Cartoon, Table...": "e.g. Cartoon, Table...",
    "Essay Topic(s)": "Essay Topic(s)",
    "Select or type topic...": "Select or type topic...",
    "Question Content / Text": "Question Content / Text",
    "Type the full question text or essay prompt here...": "Type the full question text or essay prompt here...",
    "Exam Paper Details": "Exam Paper Details",
    "Exam Title (e.g., 2024 Midterm)": "Exam Title (e.g., 2024 Midterm)",
    "Main Exam PDF (Required)": "Main Exam PDF (Required)",
    "Separate Answer Key PDF (Optional - if not in main PDF)": "Separate Answer Key PDF (Optional - if not in main PDF)",
    "Questions": "Questions",
    "Question": "Question",
    "Topic": "Topic",
    "N/A for Essay": "N/A for Essay",
    "Select...": "Select...",
    "Question Pages (e.g. 1-3)": "Question Pages (e.g. 1-3)",
    "Answer Pages (e.g. 10-11)": "Answer Pages (e.g. 10-11)",
    "From Ans PDF": "From Ans PDF",
    "From Main PDF": "From Main PDF",
    "Add Sub": "Add Sub",
    "Q-Type...": "Q-Type...",
    "Question content...": "Question content...",
    "Main PDF": "Main PDF",
    "Answer PDF": "Answer PDF",
    "Upload Main PDF to preview": "Upload Main PDF to preview",
    "Upload Answer PDF to preview": "Upload Answer PDF to preview",
    "Student Sample Details": "Student Sample Details",
    "Language": "Language",
    "English": "English",
    "Chinese": "Chinese",
    "Overall Grade": "Overall Grade",
    "e.g. 5*": "e.g. 5*",
    "Full Student Sample Document (PDF)": "Full Student Sample Document (PDF)",
    "*Optional (Leave blank to keep existing)": "*Optional (Leave blank to keep existing)",
    "*Required": "*Required",
    "Individual Question Scores & Page Splitting": "Individual Question Scores & Page Splitting",
    "Link this sample to specific questions (e.g. \"2016D Q3\"). Specify the pages (e.g., \"1, 3-5\") to split and save only those pages.": "Link this sample to specific questions (e.g. \"2016D Q3\"). Specify the pages (e.g., \"1, 3-5\") to split and save only those pages.",
    "Question Tag": "Question Tag",
    "Pages (e.g. 1, 3-5)": "Pages (e.g. 1, 3-5)",
    "e.g. 2016D Q1": "e.g. 2016D Q1",
    "Total Mark": "Total Mark",
    "Attached PDF": "Attached PDF",
    "View": "View",
    "Use Pending": "Use Pending",
    "Remove": "Remove",
    "Loading PDF Viewer...": "Loading PDF Viewer...",
    "Delete Document": "Delete Document",
    "Are you sure?": "Are you sure?",
    "Yes, Delete": "Yes, Delete",
    "Cancel": "Cancel",
    "Processing...": "Processing...",
    "Update Archive": "Update Archive",
    "Upload Data": "Upload Data",
    "Assessment Marks": "Assessment Marks",
    "Showing marks linked to:": "Showing marks linked to:",
    "No assessment marks linked to this document yet.": "No assessment marks linked to this document yet.",
    "Student": "Student",
    "Class": "Class",
    "Assessment": "Assessment",
    "Report Document Issue": "Report Document Issue",
    "Reason for reporting": "Reason for reporting",
    "Select a reason...": "Select a reason...",
    "Wrong deployment of files": "Wrong deployment of files",
    "Missing/wrong pages": "Missing/wrong pages",
    "Difficult to view": "Difficult to view",
    "Spelling mistakes of questions": "Spelling mistakes of questions",
    "No answer attached": "No answer attached",
    "Wrong tags": "Wrong tags",
    "Others (Please specify)": "Others (Please specify)",
    "Details": "Details",
    "Please provide more details...": "Please provide more details...",
    "Submitting...": "Submitting...",
    "Submit Report": "Submit Report",
    "Link Document to Archive": "Link Document to Archive",
    "Where would you like to add": "Where would you like to add",
"Add to Question Bank": "Add to Question Bank",
    "New Document": "New Document",
    "Current Document": "Current Document",
    "Add to Student Samples": "Add to Student Samples",
    "New Sample": "New Sample",
    "Current Sample": "Current Sample",
    "Student Work & Quizzes": "Student Work & Quizzes",
    "Done Editing": "Done Editing",
    "Edit List": "Edit List",
    "Add Item": "Add Item",
    "Mark All as Done": "Mark All as Done",
    "Clear All": "Clear All",
    "Are you sure you want to mark all previous exercises as done?": "Are you sure you want to mark all previous exercises as done?",
    "Are you sure you want to clear all previous exercises as done?": "Are you sure you want to clear all previous exercises as done?",
    "Delete this item from the list?": "Delete this item from the list?",
    "Performance Overview": "Performance Overview",
    "Exclude missing marks": "Exclude missing marks",
    "Percentage (%)": "Percentage (%)",
    "Percentile": "Percentile",
    "Class Average (%)": "Class Average (%)",
    "No data available for the selected categories.": "No data available for the selected categories.",
    "Performance by Topic": "Performance by Topic",
    "Topic Area": "Topic Area",
    "Average Score": "Average Score",
    "Strongest ↓": "Strongest ↓",
    "Weakest": "Weakest",
    "Paper Breakdown": "Paper Breakdown",
    "Student Consistency (Average Percentile)": "Student Consistency (Average Percentile)",
    "All Topics": "All Topics",
    "Student Name": "Student Name",
    "Assessments Taken": "Assessments Taken",
    "Avg Percentile": "Avg Percentile",
    "No data found for the selected topic.": "No data found for the selected topic.",
    "Most Consistent High ↓": "Most Consistent High ↓",
    "Lowest Percentile": "Lowest Percentile",
    "Info": "Info",
    "Term": "Term",
    "No.": "No.",
    "Name of Work": "Name of Work",
    "Action": "Action",
    "No assignments or quizzes found.": "No assignments or quizzes found.",
    "Unassigned": "Unassigned",
    "To be disclosed": "To be disclosed",
    "Generated (Dummy)": "Generated (Dummy)",
    "Available after disclosure": "Available after disclosure",
    "Click to view teacher's comment": "Click to view teacher's comment",
    "Teacher's Comment": "Teacher's Comment",
    "Edit Item": "Edit Item",
    "Add New Item": "Add New Item",
    "Name": "Name",
    "Origin (Category)": "Origin (Category)",
    "Practice": "Practice",
    "Quizzes": "Quizzes",
    "Internal Assessment": "Internal Assessment",
    "Assignments": "Assignments",
    "Full Mark": "Full Mark",
    "Date": "Date",
    "Attach Question Set": "Attach Question Set",
    "Search question sets...": "Search question sets...",
    "-- No File Attached --": "-- No File Attached --",
    "Save Item": "Save Item"
  },
  zh: {
    "HISTORY ARCHIVE": "歷史問題庫",
    "Search Engine": "搜尋引擎",
    "DSE Trend Analysis": "DSE 趨勢分析",
    "Student Dashboard": "學習進程",
    "Saved Lists": "已儲存列表",
    "PDF Tools": "PDF 工具",
    "Record Management": "記錄管理",
    "Marks Management": "分數管理",
    "Sign in": "登入",
    "Sign Out": "登出",
    "Access Denied": "拒絕訪問",
    "Admin Mode": "管理員模式",
    "Viewer Mode": "檢視者模式",
    "Access": "權限",
    "Samples": "樣本",
    "Upload": "上傳",
    "Access Restricted": "限制訪問",
    "Unauthorized Access": "未經授權的訪問",
    "Active Filters": "使用中的篩選",
    "Hide Filters": "隱藏篩選",
    "Show Filters": "顯示篩選",
    "Manage Tags": "管理標籤",
    "Reset All": "重設全部",
    "Tier Level (Admin Only)": "層級 (僅限管理員)",
    "Origin": "來源",
    "Year": "年份",
    "Paper Type": "試卷類型",
    "Question Type": "題目類型",
    "Source Type": "資料類型",
    "Topics": "課題",
    "Marks": "分數",
    "Search topics, types...": "搜尋課題、類型...",
    "View Full Paper": "檢視完整試卷",
    "View Details": "檢視詳情",
    "Edit Parent": "編輯主文件",
    "Mark as Done": "標記為完成",
    "Done": "已完成",
    "No options available": "沒有可用選項",
    "Selected": "已選取",
    "Add another...": "新增另一個...",
    "No matches found": "找不到相符項目",
    "Start typing to search": "開始輸入以搜尋",
    "Add": "新增",
    "Show": "顯示",
    "results per page": "每頁結果",
    "Verifying Access...": "正在驗證權限...",
    "Found": "找到",
    "sub-questions": "個子題",
    "papers": "份試卷",
    "Secure Database Access": "安全資料庫存取",
    "You must be logged in to view the archive contents.": "您必須登入才能檢視檔案內容。",
    "Login with Google": "使用 Google 登入",
    "Your account": "您的帳戶",
    "does not have permission to view these documents.": "沒有權限檢視這些文件。",
    "Please contact the administrator to request access.": "請聯絡管理員以要求權限。",
    "Select Paper Type first": "請先選擇試卷類型",
    "Paper 1 (DBQ)": "卷一 (資料題)",
    "Paper 2 (Essay)": "卷二 (論述題)",
    "Only available for Paper 1": "僅適用於卷一",
    "Year (Newest)": "年份 (從新到舊)",
    "Year (Oldest)": "年份 (從舊到新)",
    "Title (A-Z)": "標題 (A-Z)",
    "Date Added (Newest)": "新增日期 (從新到舊)",
    "Topic (A-Z)": "課題 (A-Z)",
    "Question Type (A-Z)": "題目類型 (A-Z)",
    "Star / To-Do Later": "標記星號 / 稍後處理",
    "Reports Attached": "附有回報",
    "[Extra Practice]": "[額外練習]",
    "Contains": "包含",
    "matched": "個相符",
    "Hide Questions": "隱藏題目",
    "Show Questions": "顯示題目",
    "Hide": "隱藏",
    "No text content provided.": "未提供文字內容。",
    "PDF": "PDF",
    "Ans": "答案",
    "Edit": "編輯",
    "PDF Attached": "已附加 PDF",
    "No PDF attached": "未附加 PDF",
    "Answer Key Available": "提供答案",
    "View Marks": "檢視分數",
    "No questions found matching your criteria.": "找不到符合您條件的題目。",
    "Manage Student Samples": "管理學生樣本",
    "View or delete uploaded student samples organized by year.": "檢視或刪除依年份整理的已上傳學生樣本。",
    "Grade:": "等級：",
    "Tags:": "標籤：",
    "Reported Issue": "已回報問題",
    "Clear this Report": "清除此回報",
    "System Update": "系統更新",
    "Don't show this again": "不要再顯示",
    "OK, Got it!": "好的，我知道了！",
    "Manage Access & Roles": "管理權限與角色",
    "Configure users, roles, and automated tier unlocking.": "設定使用者、角色和自動層級解鎖。",
    "Users & Roles": "使用者與角色",
    "Tier Access Control": "層級存取控制",
    "Google Email Address": "Google 電子郵件地址",
    "Role": "角色",
    "Add User": "新增使用者",
    "Email Address": "電子郵件地址",
    "Actions": "操作",
    "No users found.": "找不到使用者。",
    "Custom Roles": "自訂角色",
    "New role name...": "新角色名稱...",
    "Rename Tiers": "重新命名層級",
    "You can rename tiers here. Ordered 10 (Highest) to 1.": "您可以在此處重新命名層級。順序為 10 (最高) 到 1。",
    "Automated Tier Unlocking": "自動層級解鎖",
    "Select a user role below, then configure the specific date when each tier becomes visible to them.": "在下方選擇使用者角色，然後設定每個層級對他們可見的特定日期。",
    "You can also check \"Immediate Access\" to grant access right away.": "您也可以勾選「立即存取」以立即授予權限。",
    "Note: Access is cumulative!": "注意：權限是累積的！",
    "Unlocking a higher tier (e.g., Tier 5) automatically grants access to all lower tiers (1-4).": "解鎖較高層級 (例如：第 5 層級) 會自動授予所有較低層級 (1-4) 的權限。",
    "Select Role": "選擇角色",
    "Group": "群組",
    "Unlock Dates for:": "解鎖日期：",
    "Immediate Access": "立即存取",
    "Clear Date": "清除日期",
    "Bulk Update Document Tiers": "批次更新文件層級",
    "Force all existing documents in the archive to a specific tier (e.g., your S6 DSE tier).": "強制將檔案庫中所有現有文件設為特定層級 (例如：您的中六 DSE 層級)。",
    "Apply to All Documents": "套用至所有文件",
    "Save All Settings & Access": "儲存所有設定與權限",
    "Manage Filter Tags": "管理篩選標籤",
    "Note:": "注意：",
    "Deleting a tag here removes it from the filter list for this session. To permanently delete a tag, you must edit the questions that contain it.": "在此處刪除標籤會將其從此工作階段的篩選清單中移除。若要永久刪除標籤，您必須編輯包含該標籤的題目。",
    "Source Types": "資料類型",
    "Question Types (DBQ)": "題目類型 (資料題)",
    "Question Types (Essay)": "題目類型 (論述題)",
    "Answer Key: ": "答案：",
    "Full Paper View": "完整試卷檢視",
    "Report": "回報",
    "Answer": "答案",
    "Back": "返回",
    "View & Download": "檢視與下載",
    "Download": "下載",
    "Paper Overview": "試卷總覽",
    "All Sub-Questions": "所有子題",
    "No text content available.": "沒有可用的文字內容。",
    "Question Content": "題目內容",
    "No text content available. Please refer to the PDF.": "沒有可用的文字內容。請參閱 PDF。",
    "Student Samples": "學生樣本",
    "Mark (High to Low)": "分數 (從高到低)",
    "Language (EN to CH)": "語言 (英到中)",
    "Both (Lang then Mark)": "兩者 (先語言後分數)",
    "There is currently no sample available.": "目前沒有可用的樣本。",
    "Overall grade:": "整體等級：",
    "Mark (this question): ": "分數 (此題)：",
    "View Sample": "檢視樣本",
    "View PDF": "檢視 PDF",
    "No answer file available.": "沒有可用的答案檔案。",
    "Select Upload Type": "選擇上傳類型",
    "Choose what kind of document you want to add to the archive.": "選擇您要新增至檔案庫的文件種類。",
    "Edit Question Set": "編輯題目集",
    "Upload New Question Set": "上傳新題目集",
    "Add or modify a parent document and its sub-questions.": "新增或修改主文件及其子題。",
    "Batch Exam Paper Upload": "批次試卷上傳",
    "Upload a full exam PDF and split it into multiple questions.": "上傳完整試卷 PDF 並將其拆分為多個題目。",
    "Upload Student Sample": "上傳學生樣本",
    "Upload student answers, assign grades, and link to specific questions.": "上傳學生答案、分配等級，並連結至特定題目。",
    "Question Set": "題目集",
    "Upload exam papers, mock tests, and their sub-questions.": "上傳試卷、模擬試題及其子題。",
    "Batch Exam Paper": "批次試卷",
    "Upload a full exam PDF, split pages, and categorize multiple DBQ/Essays at once.": "上傳完整試卷 PDF、拆分頁面，並一次分類多個資料題/論述題。",
    "Student Sample": "學生樣本",
    "Parent Document Details": "主文件詳情",
    "Document Title": "文件標題",
    "Auto-detects \"2012D\" or \"2013E\"": "自動偵測「2012D」或「2013E」",
    "e.g. 2021E (Type '2012D' to auto-select DBQ)": "例如：2021E (輸入 '2012D' 自動選擇資料題)",
    "Select Paper": "選擇試卷",
    "Document Tier Level": "文件層級",
    "Main Topic(s) (Paper 1 Only)": "主要課題 (僅限卷一)",
    "Not applicable": "不適用",
    "Select or type new topic...": "選擇或輸入新課題...",
    "Select Origin": "選擇來源",
    "PDF Document (Question)": "PDF 文件 (題目)",
    "Optional": "選填",
    "Selected:": "已選取：",
    "Attach Pending:": "附加待處理：",
    "Answer Document (PDF)": "答案文件 (PDF)",
    "Sub-Questions (Children)": "子題",
    "Add Question": "新增題目",
    "Label": "標籤",
    "Question Type(s)": "題目類型",
    "Select or add type...": "選擇或新增類型...",
    "e.g. 4": "例如：4",
    "e.g. Cartoon, Table...": "例如：漫畫、表格...",
    "Essay Topic(s)": "論述題課題",
    "Select or type topic...": "選擇或輸入課題...",
    "Question Content / Text": "題目內容 / 文字",
    "Type the full question text or essay prompt here...": "在此輸入完整題目文字或論述題提示...",
    "Exam Paper Details": "試卷詳情",
    "Exam Title (e.g., 2024 Midterm)": "考試標題 (例如：2024 期中考)",
    "Main Exam PDF (Required)": "主要考試 PDF (必填)",
    "Separate Answer Key PDF (Optional - if not in main PDF)": "獨立答案 PDF (選填 - 如果不在主要 PDF 中)",
    "Questions": "題目",
    "Question": "題目",
    "Topic": "課題",
    "N/A for Essay": "論述題不適用",
    "Select...": "選擇...",
    "Question Pages (e.g. 1-3)": "題目頁數 (例如：1-3)",
    "Answer Pages (e.g. 10-11)": "答案頁數 (例如：10-11)",
    "From Ans PDF": "來自答案 PDF",
    "From Main PDF": "來自主要 PDF",
    "Add Sub": "新增子題",
    "Q-Type...": "題目類型...",
    "Question content...": "題目內容...",
    "Main PDF": "主要 PDF",
    "Answer PDF": "答案 PDF",
    "Upload Main PDF to preview": "上傳主要 PDF 以預覽",
    "Upload Answer PDF to preview": "上傳答案 PDF 以預覽",
    "Student Sample Details": "學生樣本詳情",
    "Language": "語言",
    "English": "英文",
    "Chinese": "中文",
    "Overall Grade": "整體等級",
    "e.g. 5*": "例如：5*",
    "Full Student Sample Document (PDF)": "完整學生樣本文件 (PDF)",
    "*Optional (Leave blank to keep existing)": "*選填 (留白以保留現有)",
    "*Required": "*必填",
    "Individual Question Scores & Page Splitting": "個別題目分數與頁面拆分",
    "Link this sample to specific questions (e.g. \"2016D Q3\"). Specify the pages (e.g., \"1, 3-5\") to split and save only those pages.": "將此樣本連結至特定題目 (例如：\"2016D Q3\")。指定頁數 (例如：\"1, 3-5\") 以拆分並僅儲存這些頁面。",
    "Question Tag": "題目標籤",
    "Pages (e.g. 1, 3-5)": "頁數 (例如：1, 3-5)",
    "e.g. 2016D Q1": "例如：2016D Q1",
    "Total Mark": "總分",
    "Attached PDF": "已附加 PDF",
    "View": "檢視",
    "Use Pending": "使用待處理",
    "Remove": "移除",
    "Loading PDF Viewer...": "正在載入 PDF 檢視器...",
    "Delete Document": "刪除文件",
    "Are you sure?": "您確定嗎？",
    "Yes, Delete": "是，刪除",
    "Cancel": "取消",
    "Processing...": "處理中...",
    "Update Archive": "更新檔案庫",
    "Upload Data": "上傳資料",
    "Assessment Marks": "評估分數",
    "Showing marks linked to:": "顯示連結至此的分數：",
    "No assessment marks linked to this document yet.": "尚未有評估分數連結至此文件。",
    "Student": "學生",
    "Class": "班級",
    "Assessment": "評估",
    "Report Document Issue": "回報文件問題",
    "Reason for reporting": "回報原因",
    "Select a reason...": "選擇原因...",
    "Wrong deployment of files": "檔案部署錯誤",
    "Missing/wrong pages": "缺頁/頁面錯誤",
    "Difficult to view": "難以檢視",
    "Spelling mistakes of questions": "題目拼寫錯誤",
    "No answer attached": "未附答案",
    "Wrong tags": "標籤錯誤",
    "Others (Please specify)": "其他 (請說明)",
    "Details": "詳情",
    "Please provide more details...": "請提供更多詳情...",
    "Submitting...": "提交中...",
    "Submit Report": "提交回報",
    "Link Document to Archive": "將文件連結至檔案庫",
    "Where would you like to add": "您想新增至何處",
"Add to Question Bank": "新增至題庫",
    "New Document": "新文件",
    "Current Document": "現有文件",
    "Add to Student Samples": "新增至學生樣本",
    "New Sample": "新樣本",
    "Current Sample": "現有樣本",
    "Student Work & Quizzes": "學生作業與測驗",
    "Done Editing": "完成編輯",
    "Edit List": "編輯列表",
    "Add Item": "新增項目",
    "Mark All as Done": "全部標記為完成",
    "Clear All": "清除全部",
    "Are you sure you want to mark all previous exercises as done?": "您確定要將所有先前的練習標記為已完成嗎？",
    "Are you sure you want to clear all previous exercises as done?": "您確定要清除所有先前的練習完成紀錄嗎？",
    "Delete this item from the list?": "從列表中刪除此項目？",
    "Performance Overview": "表現總覽",
    "Exclude missing marks": "排除缺席分數",
    "Percentage (%)": "百分比 (%)",
    "Percentile": "百分位數",
    "Class Average (%)": "班級平均 (%)",
    "No data available for the selected categories.": "所選類別沒有可用數據。",
    "Performance by Topic": "各課題表現",
    "Topic Area": "課題領域",
    "Average Score": "平均分數",
    "Strongest ↓": "最強 ↓",
    "Weakest": "最弱",
    "Paper Breakdown": "試卷細分",
    "Student Consistency (Average Percentile)": "學生穩定度 (平均百分位數)",
    "All Topics": "所有課題",
    "Student Name": "學生姓名",
    "Assessments Taken": "已完成評估",
    "Avg Percentile": "平均百分位數",
    "No data found for the selected topic.": "找不到所選課題的數據。",
    "Most Consistent High ↓": "最穩定高分 ↓",
    "Lowest Percentile": "最低百分位數",
    "Info": "資訊",
    "Term": "學期",
    "No.": "編號",
    "Name of Work": "作業名稱",
    "Action": "操作",
    "No assignments or quizzes found.": "找不到作業或測驗。",
    "Unassigned": "未分配",
    "To be disclosed": "待公佈",
    "Generated (Dummy)": "生成 (測試)",
    "Available after disclosure": "公佈後可見",
    "Click to view teacher's comment": "點擊查看老師評語",
    "Teacher's Comment": "老師評語",
    "Edit Item": "編輯項目",
    "Add New Item": "新增項目",
    "Name": "名稱",
    "Origin (Category)": "來源 (類別)",
    "Practice": "練習",
    "Quizzes": "測驗",
    "Internal Assessment": "校內評估",
    "Assignments": "作業",
    "Full Mark": "滿分",
    "Date": "日期",
    "Attach Question Set": "附加題目集",
    "Search question sets...": "搜尋題目集...",
    "No File Attached": "未附加檔案",
    "No file attached": "未附加檔案",
    "Save Item": "儲存項目",
    "Exam": "考試",
    "Uniform Test": "統測",
    "China": "中國",
    "First World War": "一戰",
    "Second World War": "二戰",
    "Cold War": "冷戰",
    "Hong Kong": "香港",
    "Japan": "日本",
    "International Cooperation": "國際合作",
    "MARK": "分數",
    "Others": "其他",
    "Score": "分數",
    "DSE Pastpaper": "DSE試題",
    "Internal School Exam": "校內試題",
    "Mock Examination":"模擬試題",
    "Quiz":"小測",
    "Exercise":"練習"
  }
};

export const LanguageProvider = ({ children }) => {
  const { user } = useAuth();
  const [language, setLangState] = useState('en');

  useEffect(() => {
    if (user?.email) {
      getDoc(doc(db, "user_progress", user.email.toLowerCase().trim()))
        .then(docSnap => {
          if (docSnap.exists() && docSnap.data().language) {
            setLangState(docSnap.data().language);
          }
        }).catch(e => console.warn("Error fetching language:", e));
    }
  }, [user]);

  const setLanguage = async (newLang) => {
    setLangState(newLang);
    if (user?.email) {
      try {
        await setDoc(doc(db, "user_progress", user.email.toLowerCase().trim()), { language: newLang }, { merge: true });
      } catch (e) { console.warn("Error saving language:", e); }
    }
  };

const t = (text) => {
    if (language === 'zh' && typeof text === 'string') {
      // Automatically catch "4 Marks", "7/8 Marks", "1 Mark", etc.
      const match = text.match(/^([\d\+\/]+)\s*Marks?$/i);
      if (match) return `${match[1]}分`;
    }
    return uiTranslations[language]?.[text] || text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);